import json
import os
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional

from fastapi import Depends, FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

SKILL_CREATOR_API_KEY = os.getenv("SKILL_CREATOR_API_KEY", "")
SKILL_STORAGE_DIR = os.getenv("SKILL_STORAGE_DIR", "./skill_registry")

storage_dir = Path(SKILL_STORAGE_DIR)
storage_dir.mkdir(parents=True, exist_ok=True)

app = FastAPI(
    title="Thin Dynamic Skill Creator API",
    version="0.1.0",
    description="Validate, render, save, and retrieve Skill JSON generated by a Langflow Summary Agent.",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Production: restrict to your Langflow/frontend domain.
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def verify_api_key(x_api_key: Optional[str] = Header(default=None)) -> None:
    if not SKILL_CREATOR_API_KEY:
        raise HTTPException(status_code=500, detail="Server SKILL_CREATOR_API_KEY is not configured.")
    if x_api_key != SKILL_CREATOR_API_KEY:
        raise HTTPException(status_code=401, detail="Invalid X-API-Key.")


class SkillCandidateInput(BaseModel):
    """
    This model is filled by the Langflow Summary Agent.
    The API does not decide semantic content.
    """
    conversation_id: Optional[str] = Field(default=None)
    source_system: str = Field(default="Langflow")
    source_summary: Optional[str] = Field(default=None)

    skill_name: str = Field(min_length=4)
    scenario_description: str = Field(min_length=20)
    trigger_conditions: List[str] = Field(min_length=1)
    anti_trigger_conditions: List[str] = Field(min_length=1)
    prompt_fragment: str = Field(min_length=20)

    workflow_orchestration_guide: List[str] = Field(
        min_length=3,
        description="Must be generated from the whole Q&A content, not from a fixed generic workflow.",
    )

    input_requirements: List[str] = Field(default_factory=list)
    tool_requirements: List[str] = Field(default_factory=list)
    output_contract: str = Field(min_length=10)
    validation_checklist: List[str] = Field(min_length=1)
    risk_notes: List[str] = Field(default_factory=list)
    reusable_pattern: str = Field(min_length=20)
    non_reusable_details_to_avoid: List[str] = Field(default_factory=list)
    status: Literal["draft", "validated", "needs_review"] = Field(default="draft")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class SkillValidationResponse(BaseModel):
    is_valid: bool
    score: int
    warnings: List[str]
    suggestions: List[str]


class SkillRecord(BaseModel):
    skill_id: str
    version: str
    created_at: str
    updated_at: str
    skill_json: SkillCandidateInput
    skill_markdown: str
    validation: SkillValidationResponse


class SkillCreateResponse(BaseModel):
    saved: bool
    skill_id: str
    version: str
    created_at: str
    skill_json: SkillCandidateInput
    skill_markdown: str
    validation: SkillValidationResponse
    files: Dict[str, str]


class SkillListItem(BaseModel):
    skill_id: str
    version: str
    skill_name: str
    status: str
    score: int
    created_at: str
    updated_at: str


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^\w\u4e00-\u9fff]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value[:80] or "skill"


def skill_paths(skill_id: str) -> Dict[str, Path]:
    folder = storage_dir / skill_id
    folder.mkdir(parents=True, exist_ok=True)
    return {
        "folder": folder,
        "json": folder / "skill.json",
        "markdown": folder / "skill.md",
        "record": folder / "record.json",
    }


def bullet(items: List[str]) -> str:
    if not items:
        return "- 無"
    return "\n".join(f"- {item}" for item in items)


def render_skill_markdown(skill: SkillCandidateInput, skill_id: Optional[str] = None, version: str = "0.1.0") -> str:
    created_line = f"- skill_id: {skill_id}\n- version: {version}\n" if skill_id else f"- version: {version}\n"
    return f"""# {skill.skill_name}

## 0. Metadata

{created_line}- source_system: {skill.source_system}
- conversation_id: {skill.conversation_id or "未提供"}
- status: {skill.status}

---

## 1. 使用場景描述

{skill.scenario_description}

---

## 2. 觸發條件

{bullet(skill.trigger_conditions)}

---

## 3. 不使用條件

{bullet(skill.anti_trigger_conditions)}

---

## 4. 行為描述 Prompt Fragment

{skill.prompt_fragment}

---

## 5. 工作流程編排指引

> 本欄位必須由 Langflow Summary Agent 根據整個問答內容產生。  
> API 不負責語意判斷，只負責驗證、渲染與儲存。

{bullet(skill.workflow_orchestration_guide)}

---

## 6. 輸入資料需求

{bullet(skill.input_requirements)}

---

## 7. 工具需求

{bullet(skill.tool_requirements)}

---

## 8. 輸出格式契約

{skill.output_contract}

---

## 9. 驗證標準

{bullet(skill.validation_checklist)}

---

## 10. 風險與限制

{bullet(skill.risk_notes)}

---

## 11. 可重用任務模式

{skill.reusable_pattern}

---

## 12. 不應寫死的一次性細節

{bullet(skill.non_reusable_details_to_avoid)}

---

## 13. Summary Agent 來源摘要

{skill.source_summary or "未提供"}
"""


def validate_skill(skill: SkillCandidateInput) -> SkillValidationResponse:
    warnings: List[str] = []
    suggestions: List[str] = []
    score = 100

    if len(skill.skill_name.strip()) < 6:
        warnings.append("技能名稱偏短，可能不夠具體。")
        suggestions.append("使用能代表可重用能力的名稱。")
        score -= 8

    if len(skill.scenario_description.strip()) < 40:
        warnings.append("使用場景描述偏短，可能無法支援 Skill Router 判斷。")
        suggestions.append("補充使用者通常如何提出此類問題，以及此 Skill 適合/不適合處理什麼。")
        score -= 10

    if len(skill.trigger_conditions) < 2:
        warnings.append("觸發條件太少。")
        suggestions.append("建議至少 2 到 5 個觸發條件。")
        score -= 8

    if len(skill.workflow_orchestration_guide) < 4:
        warnings.append("工作流程編排指引偏短，可能不足以重複執行。")
        suggestions.append("從完整問答中補充修正方向、限制條件、工具使用、最終偏好。")
        score -= 12

    workflow_text = "\n".join(skill.workflow_orchestration_guide)
    generic_phrases = ["Step 1", "Step 2", "Step 3", "理解使用者問題", "查詢資料", "輸出結果", "固定模板", "產生答案"]
    matched_generic = [phrase for phrase in generic_phrases if phrase in workflow_text]
    if len(matched_generic) >= 3:
        warnings.append("workflow_orchestration_guide 可能仍像固定模板，而不是完整問答萃取結果。")
        suggestions.append("請讓 Summary Agent 改寫 workflow，使其反映完整問答中實際形成的方法、限制與修正方向。")
        score -= 15

    if len(skill.prompt_fragment.strip()) < 40:
        warnings.append("Prompt Fragment 偏短，未來注入 Agent 時可能約束力不足。")
        suggestions.append("補充角色、行為規則、輸出要求與禁止事項。")
        score -= 10

    if len(skill.output_contract.strip()) < 20:
        warnings.append("輸出格式契約偏短。")
        suggestions.append("補充明確輸出欄位、格式、語言、表格或 Markdown 要求。")
        score -= 8

    if len(skill.validation_checklist) < 2:
        warnings.append("驗證標準太少。")
        suggestions.append("建議至少包含：是否符合原始目的、是否避免寫死一次性資訊、workflow 是否來自完整問答。")
        score -= 8

    if not skill.non_reusable_details_to_avoid:
        warnings.append("缺少不應寫死的一次性細節。")
        suggestions.append("請 Summary Agent 列出不該變成永久規則的內容。")
        score -= 6

    score = max(0, min(100, score))
    is_valid = score >= 80 and skill.status in ["validated", "needs_review"] and len(warnings) <= 2

    return SkillValidationResponse(is_valid=is_valid, score=score, warnings=warnings, suggestions=suggestions)


def save_record(record: SkillRecord) -> Dict[str, str]:
    paths = skill_paths(record.skill_id)
    paths["json"].write_text(json.dumps(record.skill_json.model_dump(), ensure_ascii=False, indent=2), encoding="utf-8")
    paths["markdown"].write_text(record.skill_markdown, encoding="utf-8")
    paths["record"].write_text(json.dumps(record.model_dump(), ensure_ascii=False, indent=2), encoding="utf-8")
    return {k: str(v) for k, v in paths.items()}


def load_record(skill_id: str) -> SkillRecord:
    paths = skill_paths(skill_id)
    if not paths["record"].exists():
        raise HTTPException(status_code=404, detail="Skill not found.")
    return SkillRecord(**json.loads(paths["record"].read_text(encoding="utf-8")))


@app.get("/health")
def health() -> Dict[str, str]:
    return {"status": "ok", "service": "thin-dynamic-skill-creator-api", "version": "0.1.0"}


@app.post("/api/v1/skills/create", response_model=SkillCreateResponse, dependencies=[Depends(verify_api_key)])
def create_skill(skill: SkillCandidateInput) -> SkillCreateResponse:
    now = datetime.now(timezone.utc).isoformat()
    skill_id = f"skill_{slugify(skill.skill_name)}_{uuid.uuid4().hex[:8]}"
    version = "0.1.0"

    validation = validate_skill(skill)
    markdown = render_skill_markdown(skill, skill_id=skill_id, version=version)

    record = SkillRecord(
        skill_id=skill_id,
        version=version,
        created_at=now,
        updated_at=now,
        skill_json=skill,
        skill_markdown=markdown,
        validation=validation,
    )
    files = save_record(record)

    return SkillCreateResponse(
        saved=True,
        skill_id=skill_id,
        version=version,
        created_at=now,
        skill_json=skill,
        skill_markdown=markdown,
        validation=validation,
        files=files,
    )


@app.post("/api/v1/skills/validate", response_model=SkillValidationResponse, dependencies=[Depends(verify_api_key)])
def validate_skill_endpoint(skill: SkillCandidateInput) -> SkillValidationResponse:
    return validate_skill(skill)


@app.post("/api/v1/skills/render", dependencies=[Depends(verify_api_key)])
def render_skill_endpoint(skill: SkillCandidateInput) -> Dict[str, str]:
    return {"skill_markdown": render_skill_markdown(skill)}


@app.get("/api/v1/skills", response_model=List[SkillListItem], dependencies=[Depends(verify_api_key)])
def list_skills() -> List[SkillListItem]:
    items: List[SkillListItem] = []
    for record_path in storage_dir.glob("*/record.json"):
        try:
            data = json.loads(record_path.read_text(encoding="utf-8"))
            skill = data["skill_json"]
            validation = data["validation"]
            items.append(
                SkillListItem(
                    skill_id=data["skill_id"],
                    version=data["version"],
                    skill_name=skill["skill_name"],
                    status=skill["status"],
                    score=validation["score"],
                    created_at=data["created_at"],
                    updated_at=data["updated_at"],
                )
            )
        except Exception:
            continue
    items.sort(key=lambda x: x.created_at, reverse=True)
    return items


@app.get("/api/v1/skills/{skill_id}", response_model=SkillRecord, dependencies=[Depends(verify_api_key)])
def get_skill(skill_id: str) -> SkillRecord:
    return load_record(skill_id)


@app.put("/api/v1/skills/{skill_id}", response_model=SkillRecord, dependencies=[Depends(verify_api_key)])
def update_skill(skill_id: str, skill: SkillCandidateInput) -> SkillRecord:
    old_record = load_record(skill_id)
    now = datetime.now(timezone.utc).isoformat()

    parts = old_record.version.split(".")
    if len(parts) == 3 and parts[-1].isdigit():
        parts[-1] = str(int(parts[-1]) + 1)
        new_version = ".".join(parts)
    else:
        new_version = f"{old_record.version}.1"

    validation = validate_skill(skill)
    markdown = render_skill_markdown(skill, skill_id=skill_id, version=new_version)

    new_record = SkillRecord(
        skill_id=skill_id,
        version=new_version,
        created_at=old_record.created_at,
        updated_at=now,
        skill_json=skill,
        skill_markdown=markdown,
        validation=validation,
    )
    save_record(new_record)
    return new_record


@app.delete("/api/v1/skills/{skill_id}", dependencies=[Depends(verify_api_key)])
def delete_skill(skill_id: str) -> Dict[str, Any]:
    paths = skill_paths(skill_id)
    if not paths["folder"].exists():
        raise HTTPException(status_code=404, detail="Skill not found.")
    for p in paths["folder"].glob("*"):
        p.unlink()
    paths["folder"].rmdir()
    return {"deleted": True, "skill_id": skill_id}
